services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile.ultra-lightweight
    container_name: portfolio-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs:/var/log/nginx
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
